PULP_APP = link_test
PULP_APP_FC_SRCS = link_test.c
PULP_APP_HOST_SRCS = link_test.c
PULP_CFLAGS = -O0 -g

include $(PULP_SDK_HOME)/install/rules/pulp_rt.mk
.PHONY: run
run:
	@echo "Don't try to run this application. It would take ages to preload the binary into memory. Just try to compile it and check the symbols with readelf of nm."
